// Recetas de demostración (las 20 del frontend original, ahora completas).
// `alimento` debe coincidir con un `nombre` de datos/alimentos.js para que el
// ingrediente quede enlazado con la tabla nutricional.
// `valoracionObjetivo` es la media que se quiere aproximar al generar valoraciones.

const img = (foto) => `https://images.unsplash.com/${foto}?w=1200&h=800&fit=crop`;
const ing = (nombre, cantidad, unidad, alimento = null, nota = null) => ({ nombre, cantidad, unidad, alimento, nota });
const paso = (titulo, descripcion, tiempoMin = null, consejo = null) => ({ titulo, descripcion, tiempoMin, consejo });
const nut = (calorias, proteinas, carbohidratos, grasas, fibra, azucares, sodio) => ({ calorias, proteinas, carbohidratos, grasas, fibra, azucares, sodio });

export const RECETAS = [
  {
    id: 1,
    titulo: 'Ensalada César con Pollo',
    autor: 'maria',
    imagenUrl: img('photo-1546793665-c74683f339c1'),
    categoria: 'Ensaladas',
    dificultad: 'Fácil',
    tiempoTotal: 20, tiempoPreparacion: 15, tiempoCoccion: 5,
    porciones: 4,
    etiquetas: ['Proteína', 'Vegetales', 'Saludable'],
    descripcion: 'Una ensalada clásica con pollo grillado, lechuga romana fresca y aderezo César casero. Perfecta para una comida ligera pero satisfactoria.',
    nutricion: nut(420, 32, 18, 26, 4, 3, 680),
    valoracionObjetivo: 4.8,
    ingredientes: [
      ing('Lechuga romana', 400, 'g', 'Lechuga romana', '2 cabezas'),
      ing('Pechuga de pollo', 400, 'g', 'Pechuga de pollo'),
      ing('Pan baguette', 150, 'g', 'Pan baguette', 'para los crutones'),
      ing('Queso parmesano', 80, 'g', 'Queso parmesano'),
      ing('Huevos', 2, 'unidades', 'Huevo'),
      ing('Aceite de oliva virgen extra', 4, 'cucharadas', 'Aceite de oliva virgen extra'),
      ing('Ajo', 2, 'dientes', 'Ajo'),
      ing('Anchoas en aceite', 4, 'filetes', 'Anchoas en aceite'),
      ing('Zumo de limón', 2, 'cucharadas', 'Limón'),
      ing('Mostaza de Dijon', 1, 'cucharadita', 'Mostaza de Dijon'),
      ing('Sal y pimienta', null, 'al gusto'),
    ],
    pasos: [
      paso('Preparar el pollo', 'Sazona las pechugas con sal y pimienta. Calienta una sartén con un poco de aceite y cocina el pollo 6-8 minutos por cada lado hasta que esté dorado y hecho por completo.', 10, 'La temperatura interna del pollo debe alcanzar 74 °C'),
      paso('Hacer los crutones', 'Corta el pan en cubos de 2 cm. Mézclalos con aceite de oliva, sal y ajo picado. Hornea a 180 °C durante 8-10 minutos hasta que estén dorados y crujientes.', 12, 'Remueve los crutones a mitad de cocción para que se doren uniformemente'),
      paso('Preparar el aderezo', 'Mezcla las yemas, la mostaza, las anchoas picadas, el ajo prensado y el zumo de limón. Añade el aceite poco a poco mientras bates hasta obtener una salsa cremosa.', 5, 'Añade el aceite gota a gota al principio para que no se corte'),
      paso('Montar la ensalada', 'Lava y corta la lechuga. Mézclala con el aderezo, añade el pollo en tiras, los crutones y el parmesano rallado. Sirve inmediatamente.', 3, 'Sirve en platos fríos para mantener la frescura'),
    ],
    valoraciones: [
      { usuario: 'ana', puntuacion: 5, comentario: '¡Increíble! El aderezo casero marca la diferencia. A toda la familia le encantó.' },
      { usuario: 'carlos', puntuacion: 4, comentario: 'Muy buena receta. Los crutones quedaron perfectos. La repetiré.' },
    ],
  },
  {
    id: 2,
    titulo: 'Pasta Carbonara Auténtica',
    autor: 'giuseppe',
    imagenUrl: img('photo-1621996346565-e3dbc353d2e5'),
    categoria: 'Pasta',
    dificultad: 'Medio',
    tiempoTotal: 25, tiempoPreparacion: 10, tiempoCoccion: 15,
    porciones: 3,
    etiquetas: ['Italiana', 'Comfort Food', 'Tradicional'],
    descripcion: 'La receta tradicional italiana con huevos, panceta, queso pecorino y pimienta negra. Sin nata: solo los ingredientes auténticos.',
    nutricion: nut(580, 28, 52, 32, 3, 2, 890),
    valoracionObjetivo: 4.9,
    ingredientes: [
      ing('Espaguetis', 400, 'g', 'Espaguetis'),
      ing('Panceta', 200, 'g', 'Panceta', 'o guanciale'),
      ing('Huevos enteros', 3, 'unidades', 'Huevo'),
      ing('Yemas de huevo', 2, 'unidades', 'Yema de huevo'),
      ing('Queso pecorino romano', 100, 'g', 'Queso pecorino romano', 'rallado fino'),
      ing('Pimienta negra', null, 'al gusto', 'Pimienta negra', 'recién molida'),
      ing('Sal', null, 'al gusto', 'Sal', 'para el agua'),
    ],
    pasos: [
      paso('Preparar la panceta', 'Corta la panceta en dados pequeños y dórala en una sartén grande a fuego medio hasta que esté crujiente.', 8, 'No añadas aceite: la panceta suelta su propia grasa'),
      paso('Cocer la pasta', 'Hierve agua con sal abundante y cuece la pasta al dente según el paquete.', 10, 'Reserva una taza del agua de cocción antes de escurrir'),
      paso('Preparar la mezcla de huevo', 'Bate los huevos con las yemas, el pecorino rallado y pimienta negra abundante.', 3, 'El queso debe estar muy fino para que no haga grumos'),
      paso('Mezclar todo', 'Escurre la pasta y pásala a la sartén con la panceta. Retira del fuego y añade la mezcla de huevo removiendo rápido; ajusta con agua de cocción.', 4, 'El calor residual cuaja el huevo sin hacerlo tortilla'),
    ],
    valoraciones: [
      { usuario: 'isabella', puntuacion: 5, comentario: '¡La mejor carbonara que he probado! Exactamente como en Roma.' },
    ],
  },
  {
    id: 3,
    titulo: 'Salmón Teriyaki con Verduras',
    autor: 'kenji',
    imagenUrl: img('photo-1467003909585-2f8a72700288'),
    categoria: 'Pescado',
    dificultad: 'Medio',
    tiempoTotal: 30, tiempoPreparacion: 15, tiempoCoccion: 15,
    porciones: 2,
    etiquetas: ['Omega-3', 'Asiática', 'Saludable'],
    descripcion: 'Salmón glaseado con salsa teriyaki casera acompañado de verduras salteadas. Rico en omega-3 y con sabores asiáticos.',
    nutricion: nut(450, 35, 22, 25, 6, 18, 1200),
    valoracionObjetivo: 4.7,
    ingredientes: [
      ing('Salmón', 400, 'g', 'Salmón', '2 filetes de 200 g'),
      ing('Brócoli', 200, 'g', 'Brócoli'),
      ing('Zanahoria', 1, 'unidad', 'Zanahoria', 'grande'),
      ing('Pimiento rojo', 1, 'unidad', 'Pimiento rojo'),
      ing('Salsa de soja', 4, 'cucharadas', 'Salsa de soja'),
      ing('Mirin', 2, 'cucharadas', 'Mirin'),
      ing('Azúcar moreno', 2, 'cucharadas', 'Azúcar moreno'),
      ing('Jengibre fresco', 1, 'cucharada', 'Jengibre fresco', 'rallado'),
      ing('Ajo', 2, 'dientes', 'Ajo'),
      ing('Aceite de sésamo', 1, 'cucharada', 'Aceite de sésamo'),
      ing('Semillas de sésamo', 1, 'cucharada', 'Semillas de sésamo'),
    ],
    pasos: [
      paso('Preparar la salsa teriyaki', 'Mezcla la soja, el mirin, el azúcar, el jengibre y el ajo picados. Cocina a fuego lento hasta que espese.', 8, 'Está lista cuando cubre el dorso de una cuchara'),
      paso('Marinar el salmón', 'Marina los filetes con la mitad de la salsa durante 10 minutos.', 10, 'No lo marines más tiempo o el pescado se "cocinará" con la salsa'),
      paso('Saltear las verduras', 'Saltea las verduras en aceite de sésamo hasta que estén tiernas pero crujientes.', 6, 'Empieza por las más duras'),
      paso('Cocinar el salmón', 'Cocina el salmón en una sartén caliente 4 minutos por lado. Glasea con la salsa restante y espolvorea sésamo.', 8, 'La piel debe quedar crujiente y el interior jugoso'),
    ],
    valoraciones: [
      { usuario: 'pedro', puntuacion: 5, comentario: 'Sabores auténticos y muy fácil. El salmón quedó perfecto.' },
    ],
  },
  {
    id: 4,
    titulo: 'Tacos de Pescado Baja',
    autor: 'elena',
    imagenUrl: img('photo-1565299585323-38174c832fdd'),
    categoria: 'Mexicana',
    dificultad: 'Fácil',
    tiempoTotal: 15, tiempoPreparacion: 10, tiempoCoccion: 5,
    porciones: 4,
    etiquetas: ['Mexicana', 'Rápido', 'Fresco'],
    descripcion: 'Tacos frescos con pescado rebozado, lombarda y salsa de lima. Un clásico de Baja California.',
    nutricion: nut(320, 28, 35, 12, 5, 4, 520),
    valoracionObjetivo: 4.6,
    ingredientes: [
      ing('Pescado blanco', 500, 'g', 'Merluza', 'merluza, bacalao o similar'),
      ing('Tortillas de maíz', 8, 'unidades', 'Tortillas de maíz'),
      ing('Lombarda', 200, 'g', 'Lombarda', 'en juliana fina'),
      ing('Limas', 3, 'unidades', 'Lima'),
      ing('Cilantro fresco', 0.5, 'taza', 'Cilantro fresco'),
      ing('Cebolla', 0.25, 'taza', 'Cebolla', 'picada'),
      ing('Mayonesa', 0.33, 'taza', 'Mayonesa'),
      ing('Harina de trigo', 1, 'taza', 'Harina de trigo'),
      ing('Cerveza', 0.5, 'taza', 'Cerveza', 'muy fría'),
      ing('Comino', 1, 'cucharadita', 'Comino'),
      ing('Pimentón', 1, 'cucharadita', 'Pimentón'),
    ],
    pasos: [
      paso('Preparar el rebozado', 'Mezcla la harina, la cerveza, el comino, el pimentón, sal y pimienta hasta obtener una masa lisa.', 3, 'Debe tener consistencia de crema espesa'),
      paso('Rebozar y freír el pescado', 'Corta el pescado en tiras, pásalas por la masa y fríelas en aceite caliente hasta dorar.', 6, 'El aceite debe estar a 180 °C'),
      paso('Preparar la ensalada', 'Mezcla la lombarda con el cilantro, la cebolla, el zumo de lima y la mayonesa.', 4, 'Añade la sal al final para que la lombarda no suelte agua'),
      paso('Montar los tacos', 'Calienta las tortillas, pon el pescado, la ensalada y un chorrito de lima.', 2, 'Sirve al momento para que el pescado siga crujiente'),
    ],
    valoraciones: [
      { usuario: 'roberto', puntuacion: 5, comentario: '¡Como los de Ensenada! Perfectos para el verano.' },
    ],
  },
  {
    id: 5,
    titulo: 'Risotto de Setas',
    autor: 'marco',
    imagenUrl: img('photo-1476124369491-e7addf5db371'),
    categoria: 'Vegetariana',
    dificultad: 'Difícil',
    tiempoTotal: 40, tiempoPreparacion: 15, tiempoCoccion: 25,
    porciones: 4,
    etiquetas: ['Vegetariana', 'Cremoso', 'Italiana'],
    descripcion: 'Cremoso risotto italiano con setas variadas y parmesano. Requiere paciencia, pero el resultado es espectacular.',
    nutricion: nut(390, 12, 58, 14, 3, 5, 750),
    valoracionObjetivo: 4.5,
    ingredientes: [
      ing('Arroz arborio', 320, 'g', 'Arroz arborio'),
      ing('Setas variadas', 400, 'g', 'Setas variadas'),
      ing('Caldo de verduras', 1500, 'ml', 'Caldo de verduras', 'caliente'),
      ing('Vino blanco', 0.5, 'taza', 'Vino blanco'),
      ing('Cebolla', 1, 'unidad', 'Cebolla', 'mediana'),
      ing('Ajo', 3, 'dientes', 'Ajo'),
      ing('Queso parmesano', 100, 'g', 'Queso parmesano'),
      ing('Mantequilla', 50, 'g', 'Mantequilla'),
      ing('Aceite de oliva virgen extra', 3, 'cucharadas', 'Aceite de oliva virgen extra'),
      ing('Perejil fresco', 2, 'cucharadas', 'Perejil fresco', 'picado'),
    ],
    pasos: [
      paso('Preparar el caldo', 'Calienta el caldo y mantenlo a fuego muy suave durante toda la cocción.', 5, 'El caldo caliente es clave para un risotto cremoso'),
      paso('Saltear las setas', 'Saltea las setas en aceite hasta dorarlas. Reserva la mitad para el final.', 8, 'No amontones las setas o soltarán agua'),
      paso('Tostar el arroz', 'Sofríe la cebolla y el ajo, añade el arroz y tuéstalo hasta que esté translúcido. Añade el vino y deja evaporar.', 5, 'El arroz debe estar bien tostado antes del líquido'),
      paso('Cocinar el risotto', 'Añade el caldo poco a poco, removiendo sin parar, hasta que el arroz esté cremoso y al dente.', 18, 'Nunca dejes de remover; añade caldo solo cuando se haya absorbido el anterior'),
      paso('Mantecar', 'Fuera del fuego incorpora la mantequilla, el parmesano, las setas reservadas y el perejil. Rectifica de sal.', 4, 'El "mantecato" final da la cremosidad característica'),
    ],
    valoraciones: [
      { usuario: 'lucia', puntuacion: 4, comentario: 'Requiere paciencia pero vale la pena. Quedó cremoso y delicioso.' },
    ],
  },
  {
    id: 6,
    titulo: 'Bowl Buddha Vegano',
    autor: 'sofia',
    imagenUrl: img('photo-1512621776951-a57141f2eefd'),
    categoria: 'Vegana',
    dificultad: 'Fácil',
    tiempoTotal: 25, tiempoPreparacion: 15, tiempoCoccion: 10,
    porciones: 2,
    etiquetas: ['Vegana', 'Nutritivo', 'Colorido'],
    descripcion: 'Bowl nutritivo con quinoa, verduras frescas, aguacate y salsa de tahini. Colorido, saludable y completamente vegano.',
    nutricion: nut(380, 15, 42, 18, 12, 8, 280),
    valoracionObjetivo: 4.4,
    ingredientes: [
      ing('Quinoa', 170, 'g', 'Quinoa', '1 taza'),
      ing('Aguacate', 1, 'unidad', 'Aguacate', 'grande'),
      ing('Espinacas baby', 60, 'g', 'Espinacas', '2 tazas'),
      ing('Zanahoria', 1, 'unidad', 'Zanahoria', 'grande'),
      ing('Pepino', 1, 'unidad', 'Pepino', 'mediano'),
      ing('Tomates cherry', 150, 'g', 'Tomates cherry'),
      ing('Garbanzos cocidos', 160, 'g', 'Garbanzos cocidos', '1 taza'),
      ing('Tahini', 3, 'cucharadas', 'Tahini'),
      ing('Zumo de limón', 2, 'cucharadas', 'Limón'),
      ing('Semillas de girasol', 2, 'cucharadas', 'Semillas de girasol'),
      ing('Aceite de oliva virgen extra', 1, 'cucharada', 'Aceite de oliva virgen extra'),
    ],
    pasos: [
      paso('Cocer la quinoa', 'Enjuaga la quinoa y cuécela en agua con sal hasta que esté tierna.', 15, 'Usa 2 partes de agua por 1 de quinoa'),
      paso('Preparar las verduras', 'Corta todas las verduras en juliana o dados. Mantén los colores separados.', 8, 'Los cortes uniformes hacen el bowl más atractivo'),
      paso('Hacer la salsa de tahini', 'Mezcla el tahini, el zumo de limón, el aceite y un poco de agua hasta lograr una crema.', 2, 'Añade el agua poco a poco'),
      paso('Montar el bowl', 'Reparte la quinoa en los bowls, coloca las verduras por colores, añade el aguacate y riega con la salsa.', 5, 'La presentación colorida es parte del atractivo'),
    ],
    valoraciones: [
      { usuario: 'carmen', puntuacion: 5, comentario: '¡Perfecto! Nutritivo, sabroso y muy fotogénico. Lo haré a menudo.' },
    ],
  },
  {
    id: 7,
    titulo: 'Pollo al Curry Tailandés',
    autor: 'kenji',
    imagenUrl: img('photo-1455619452474-d2be8b1e70cd'),
    categoria: 'Asiática',
    dificultad: 'Medio',
    tiempoTotal: 35, tiempoPreparacion: 10, tiempoCoccion: 25,
    porciones: 4,
    etiquetas: ['Picante', 'Asiática', 'Cremoso'],
    descripcion: 'Curry cremoso de leche de coco con pollo tierno y verduras. Picante equilibrado y listo en poco más de media hora.',
    nutricion: nut(520, 34, 38, 26, 4, 7, 720),
    valoracionObjetivo: 4.8,
    ingredientes: [
      ing('Muslo de pollo', 600, 'g', 'Muslo de pollo', 'deshuesado, en trozos'),
      ing('Pasta de curry rojo', 3, 'cucharadas', 'Pasta de curry rojo'),
      ing('Leche de coco', 400, 'ml', 'Leche de coco'),
      ing('Pimiento rojo', 1, 'unidad', 'Pimiento rojo', 'en tiras'),
      ing('Judías verdes', 150, 'g', 'Judías verdes'),
      ing('Cebolla', 1, 'unidad', 'Cebolla'),
      ing('Ajo', 2, 'dientes', 'Ajo'),
      ing('Jengibre fresco', 1, 'cucharada', 'Jengibre fresco', 'rallado'),
      ing('Salsa de soja', 1, 'cucharada', 'Salsa de soja'),
      ing('Azúcar moreno', 1, 'cucharadita', 'Azúcar moreno'),
      ing('Lima', 1, 'unidad', 'Lima'),
      ing('Arroz blanco', 300, 'g', 'Arroz blanco', 'para acompañar'),
      ing('Cilantro fresco', null, 'al gusto', 'Cilantro fresco'),
    ],
    pasos: [
      paso('Sofreír la base', 'Sofríe la cebolla, el ajo y el jengibre en un poco de aceite. Añade la pasta de curry y cocínala 1 minuto para despertar los aromas.', 5, 'Freír la pasta de curry intensifica mucho el sabor'),
      paso('Dorar el pollo', 'Incorpora el pollo y dóralo por todos lados con la base de curry.', 8),
      paso('Añadir el coco y las verduras', 'Vierte la leche de coco, la soja y el azúcar. Añade el pimiento y las judías y cocina a fuego medio hasta que el pollo esté tierno.', 15, 'Si espesa demasiado, añade un poco de agua o caldo'),
      paso('Servir', 'Termina con zumo de lima y cilantro. Sirve con arroz blanco.', 5, 'Cuece el arroz mientras se hace el curry'),
    ],
  },
  {
    id: 8,
    titulo: 'Bruschetta de Tomate',
    autor: 'giuseppe',
    imagenUrl: img('photo-1506084868230-bb9d95c24759'),
    categoria: 'Aperitivo',
    dificultad: 'Fácil',
    tiempoTotal: 10, tiempoPreparacion: 8, tiempoCoccion: 2,
    porciones: 6,
    etiquetas: ['Italiana', 'Fresco', 'Rápido'],
    descripcion: 'Pan tostado con tomate maduro, albahaca y buen aceite de oliva. El aperitivo italiano más sencillo y más agradecido.',
    nutricion: nut(180, 5, 26, 7, 2, 3, 310),
    valoracionObjetivo: 4.3,
    ingredientes: [
      ing('Pan de pueblo', 300, 'g', 'Pan de pueblo', '6 rebanadas'),
      ing('Tomate', 400, 'g', 'Tomate', 'maduros'),
      ing('Ajo', 2, 'dientes', 'Ajo'),
      ing('Albahaca fresca', 10, 'hojas', 'Albahaca fresca'),
      ing('Aceite de oliva virgen extra', 3, 'cucharadas', 'Aceite de oliva virgen extra'),
      ing('Sal', null, 'al gusto', 'Sal'),
      ing('Pimienta negra', null, 'al gusto', 'Pimienta negra'),
    ],
    pasos: [
      paso('Tostar el pan', 'Tuesta las rebanadas en la plancha o el horno hasta que estén doradas. Frótalas con un diente de ajo.', 4, 'El pan caliente absorbe mejor el aroma del ajo'),
      paso('Preparar el tomate', 'Corta el tomate en dados pequeños y mézclalo con la albahaca troceada, aceite, sal y pimienta.', 4, 'Escurre el exceso de agua del tomate'),
      paso('Montar', 'Reparte el tomate sobre el pan y termina con un hilo de aceite. Sirve enseguida.', 2),
    ],
  },
  {
    id: 9,
    titulo: 'Paella Valenciana',
    autor: 'maria',
    imagenUrl: img('photo-1534080564583-6be75777b70a'),
    categoria: 'Española',
    dificultad: 'Difícil',
    tiempoTotal: 45, tiempoPreparacion: 15, tiempoCoccion: 30,
    porciones: 6,
    etiquetas: ['Española', 'Tradicional', 'Festiva'],
    descripcion: 'Auténtica paella valenciana con arroz bomba, pollo, conejo y verduras. La receta de domingo por excelencia.',
    nutricion: nut(620, 38, 62, 22, 4, 3, 850),
    valoracionObjetivo: 4.9,
    ingredientes: [
      ing('Arroz bomba', 500, 'g', 'Arroz bomba'),
      ing('Pollo', 600, 'g', 'Pollo entero', 'troceado'),
      ing('Conejo', 400, 'g', 'Conejo', 'troceado'),
      ing('Judías verdes planas', 200, 'g', 'Judías verdes'),
      ing('Tomate', 200, 'g', 'Tomate', 'rallado'),
      ing('Aceite de oliva virgen extra', 100, 'ml', 'Aceite de oliva virgen extra'),
      ing('Pimentón', 1, 'cucharadita', 'Pimentón'),
      ing('Azafrán', null, 'pizca', 'Azafrán', 'unas hebras'),
      ing('Caldo de pollo', 1500, 'ml', 'Caldo de pollo', 'o agua'),
      ing('Sal', null, 'al gusto', 'Sal'),
    ],
    pasos: [
      paso('Sofreír las carnes', 'Calienta el aceite en la paella y dora bien el pollo y el conejo salpimentados.', 10, 'Un buen dorado da color y sabor al caldo'),
      paso('Añadir verduras y tomate', 'Incorpora las judías, después el tomate rallado y el pimentón. Sofríe sin que el pimentón se queme.', 5, 'Añade el pimentón justo antes del líquido para que no amargue'),
      paso('Hacer el caldo', 'Vierte el caldo, añade el azafrán y deja hervir para que las carnes suelten sabor.', 15),
      paso('Añadir el arroz', 'Reparte el arroz en forma de cruz y no lo remuevas más. Cocina a fuego fuerte 8 minutos y suave otros 10 hasta que se absorba el líquido.', 18, 'El punto de fuego es lo que da el socarrat'),
      paso('Reposar', 'Tapa con un paño y deja reposar 5 minutos antes de servir.', 5),
    ],
  },
  {
    id: 10,
    titulo: 'Ramen de Miso',
    autor: 'kenji',
    imagenUrl: img('photo-1569718212165-3a8278d5f624'),
    categoria: 'Asiática',
    dificultad: 'Medio',
    tiempoTotal: 50, tiempoPreparacion: 20, tiempoCoccion: 30,
    porciones: 2,
    etiquetas: ['Japonesa', 'Comfort Food', 'Caldo'],
    descripcion: 'Ramen casero con caldo de miso, cerdo, huevo marinado y verduras. Reconfortante y lleno de umami.',
    nutricion: nut(480, 30, 52, 16, 4, 5, 1450),
    valoracionObjetivo: 4.6,
    ingredientes: [
      ing('Fideos ramen frescos', 300, 'g', 'Fideos ramen frescos'),
      ing('Caldo de pollo', 1000, 'ml', 'Caldo de pollo'),
      ing('Pasta de miso', 3, 'cucharadas', 'Pasta de miso'),
      ing('Lomo de cerdo', 200, 'g', 'Lomo de cerdo', 'en láminas finas'),
      ing('Huevos', 2, 'unidades', 'Huevo', 'para marinar'),
      ing('Brotes de soja', 100, 'g', 'Brotes de soja'),
      ing('Cebolleta', 0.5, 'unidad', 'Cebolla', 'en rodajas finas'),
      ing('Ajo', 2, 'dientes', 'Ajo'),
      ing('Jengibre fresco', 1, 'cucharada', 'Jengibre fresco'),
      ing('Salsa de soja', 2, 'cucharadas', 'Salsa de soja'),
      ing('Alga nori', 2, 'láminas', 'Alga nori'),
      ing('Semillas de sésamo', 1, 'cucharada', 'Semillas de sésamo'),
      ing('Aceite de sésamo', 1, 'cucharada', 'Aceite de sésamo'),
    ],
    pasos: [
      paso('Cocer y marinar los huevos', 'Cuece los huevos 6 minutos y medio, enfríalos y pélalos. Mételos en soja diluida mientras preparas el resto.', 15, 'La yema debe quedar cremosa'),
      paso('Preparar el caldo', 'Sofríe el ajo y el jengibre en aceite de sésamo, añade el caldo y llévalo a ebullición. Disuelve el miso fuera del hervor.', 20, 'El miso no debe hervir o perderá aroma'),
      paso('Dorar el cerdo', 'Marca las láminas de cerdo en una sartén muy caliente con un poco de soja.', 8),
      paso('Cocer los fideos y montar', 'Cuece los fideos, repártelos en boles, cubre con caldo y coloca el cerdo, el huevo partido, los brotes, la cebolleta, el nori y el sésamo.', 7, 'Sirve inmediatamente para que los fideos no se pasen'),
    ],
  },
  {
    id: 11,
    titulo: 'Gazpacho Andaluz',
    autor: 'maria',
    imagenUrl: img('photo-1553909489-cd47e0ef937f'),
    categoria: 'Sopas',
    dificultad: 'Fácil',
    tiempoTotal: 15, tiempoPreparacion: 15, tiempoCoccion: 0,
    porciones: 4,
    etiquetas: ['Española', 'Frío', 'Vegano'],
    descripcion: 'Sopa fría tradicional con tomates maduros, pepino y pimiento. Refrescante y perfecta para el verano.',
    nutricion: nut(120, 2, 12, 8, 3, 7, 380),
    valoracionObjetivo: 4.4,
    ingredientes: [
      ing('Tomate', 1000, 'g', 'Tomate', 'muy maduros'),
      ing('Pepino', 1, 'unidad', 'Pepino'),
      ing('Pimiento verde', 1, 'unidad', 'Pimiento verde'),
      ing('Ajo', 1, 'diente', 'Ajo'),
      ing('Pan de pueblo', 50, 'g', 'Pan de pueblo', 'del día anterior'),
      ing('Aceite de oliva virgen extra', 50, 'ml', 'Aceite de oliva virgen extra'),
      ing('Vinagre de Jerez', 2, 'cucharadas', 'Vinagre de Jerez'),
      ing('Agua', 200, 'ml', 'Agua', 'fría'),
      ing('Sal', null, 'al gusto', 'Sal'),
    ],
    pasos: [
      paso('Preparar las verduras', 'Lava y trocea el tomate, el pepino y el pimiento. Remoja el pan en un poco de agua.', 8, 'Pelar el pepino evita el amargor'),
      paso('Triturar', 'Tritura todo con el ajo, el aceite, el vinagre y la sal hasta que quede muy fino. Añade agua hasta la textura deseada.', 5, 'Si quieres una textura sedosa, pásalo por un colador'),
      paso('Enfriar y servir', 'Refrigera al menos una hora y sirve muy frío con daditos de verdura por encima.', 2),
    ],
  },
  {
    id: 12,
    titulo: 'Coq au Vin',
    autor: 'marco',
    imagenUrl: img('photo-1598103442097-8b74394b95c6'),
    categoria: 'Francesa',
    dificultad: 'Difícil',
    tiempoTotal: 90, tiempoPreparacion: 20, tiempoCoccion: 70,
    porciones: 4,
    etiquetas: ['Francesa', 'Estofado', 'Elegante'],
    descripcion: 'Pollo estofado en vino tinto con cebollitas, champiñones y bacon. Un clásico francés de cocción lenta.',
    nutricion: nut(680, 48, 18, 38, 3, 6, 720),
    valoracionObjetivo: 4.7,
    ingredientes: [
      ing('Muslos de pollo', 1200, 'g', 'Muslo de pollo', 'con hueso'),
      ing('Vino tinto', 750, 'ml', 'Vino tinto'),
      ing('Bacon', 150, 'g', 'Bacon', 'en tiras'),
      ing('Champiñones', 250, 'g', 'Champiñones'),
      ing('Cebollitas francesas', 200, 'g', 'Cebollitas francesas'),
      ing('Zanahoria', 2, 'unidades', 'Zanahoria'),
      ing('Ajo', 3, 'dientes', 'Ajo'),
      ing('Caldo de pollo', 250, 'ml', 'Caldo de pollo'),
      ing('Mantequilla', 30, 'g', 'Mantequilla'),
      ing('Harina de trigo', 2, 'cucharadas', 'Harina de trigo'),
      ing('Tomate triturado', 1, 'cucharada', 'Tomate triturado'),
      ing('Sal y pimienta', null, 'al gusto'),
    ],
    pasos: [
      paso('Dorar el bacon y el pollo', 'Dora el bacon en una cazuela, retíralo y dora el pollo salpimentado en la misma grasa.', 15, 'Dora en tandas para que no se cueza en su jugo'),
      paso('Sofreír las verduras', 'Añade las cebollitas, la zanahoria y el ajo. Espolvorea la harina y remueve un minuto.', 10),
      paso('Guisar', 'Vierte el vino, el caldo y el tomate. Devuelve el pollo y el bacon y cocina tapado a fuego suave.', 60, 'El vino debe cubrir casi todo el pollo'),
      paso('Terminar', 'Saltea los champiñones en mantequilla y añádelos al final. Reduce la salsa si hace falta.', 5, 'Sirve con puré de patata o pan'),
    ],
  },
  {
    id: 13,
    titulo: 'Sushi Roll California',
    autor: 'kenji',
    imagenUrl: img('photo-1579584425555-c3ce17fd4351'),
    categoria: 'Asiática',
    dificultad: 'Medio',
    tiempoTotal: 45, tiempoPreparacion: 30, tiempoCoccion: 15,
    porciones: 4,
    etiquetas: ['Japonesa', 'Fresco', 'Elegante'],
    descripcion: 'Rollos de sushi invertidos con surimi, aguacate y pepino, cubiertos de sésamo. Ideales para empezar con el sushi casero.',
    nutricion: nut(350, 10, 58, 8, 3, 6, 620),
    valoracionObjetivo: 4.5,
    ingredientes: [
      ing('Arroz para sushi', 300, 'g', 'Arroz blanco', 'de grano corto'),
      ing('Vinagre de arroz', 3, 'cucharadas', 'Vinagre de arroz'),
      ing('Azúcar blanco', 1, 'cucharada', 'Azúcar blanco'),
      ing('Sal', 1, 'cucharadita', 'Sal'),
      ing('Alga nori', 4, 'láminas', 'Alga nori'),
      ing('Surimi', 200, 'g', 'Surimi', 'palitos de cangrejo'),
      ing('Aguacate', 1, 'unidad', 'Aguacate'),
      ing('Pepino', 1, 'unidad', 'Pepino', 'en bastones'),
      ing('Semillas de sésamo', 2, 'cucharadas', 'Semillas de sésamo'),
      ing('Mayonesa', 2, 'cucharadas', 'Mayonesa'),
      ing('Salsa de soja', null, 'al gusto', 'Salsa de soja', 'para acompañar'),
    ],
    pasos: [
      paso('Cocer y sazonar el arroz', 'Lava el arroz hasta que el agua salga clara y cuécelo. Mézclalo en caliente con el vinagre, el azúcar y la sal y deja templar.', 25, 'Abanica el arroz mientras lo mezclas para que brille'),
      paso('Preparar los rellenos', 'Corta el aguacate y el pepino en bastones y mezcla el surimi con la mayonesa.', 5),
      paso('Enrollar', 'Extiende arroz sobre el nori, espolvorea sésamo, dale la vuelta, coloca el relleno y enrolla con la esterilla apretando.', 10, 'Humedece las manos para que el arroz no se pegue'),
      paso('Cortar y servir', 'Corta cada rollo en 8 piezas con un cuchillo húmedo y sirve con soja.', 5),
    ],
  },
  {
    id: 14,
    titulo: 'Lasaña de Verduras',
    autor: 'marco',
    imagenUrl: img('photo-1565299624946-b28f40a0ca4b'),
    categoria: 'Vegetariana',
    dificultad: 'Medio',
    tiempoTotal: 60, tiempoPreparacion: 20, tiempoCoccion: 40,
    porciones: 6,
    etiquetas: ['Vegetariana', 'Comfort Food', 'Hornear'],
    descripcion: 'Lasaña por capas con berenjena, calabacín, espinacas y ricotta. Reconfortante y llena de verdura.',
    nutricion: nut(420, 22, 38, 20, 7, 11, 640),
    valoracionObjetivo: 4.6,
    ingredientes: [
      ing('Placas de lasaña', 250, 'g', 'Placas de lasaña'),
      ing('Berenjena', 1, 'unidad', 'Berenjena', 'en láminas'),
      ing('Calabacín', 2, 'unidades', 'Calabacín', 'en láminas'),
      ing('Espinacas', 300, 'g', 'Espinacas'),
      ing('Queso ricotta', 250, 'g', 'Queso ricotta'),
      ing('Queso mozzarella', 200, 'g', 'Queso mozzarella'),
      ing('Queso parmesano', 50, 'g', 'Queso parmesano'),
      ing('Tomate triturado', 500, 'g', 'Tomate triturado'),
      ing('Cebolla', 1, 'unidad', 'Cebolla'),
      ing('Ajo', 2, 'dientes', 'Ajo'),
      ing('Aceite de oliva virgen extra', 3, 'cucharadas', 'Aceite de oliva virgen extra'),
      ing('Orégano seco', 1, 'cucharadita', 'Orégano seco'),
      ing('Sal y pimienta', null, 'al gusto'),
    ],
    pasos: [
      paso('Asar las verduras', 'Pincela las láminas de berenjena y calabacín con aceite y ásalas en plancha u horno hasta dorarlas. Saltea las espinacas.', 15, 'Asar las verduras evita una lasaña aguada'),
      paso('Preparar la salsa', 'Sofríe la cebolla y el ajo, añade el tomate y el orégano y cocina 10 minutos.', 10),
      paso('Montar la lasaña', 'Alterna capas de salsa, placas, verduras, ricotta y mozzarella. Termina con salsa y parmesano.', 10),
      paso('Hornear', 'Hornea a 180 °C hasta que esté dorada y burbujeante. Deja reposar 10 minutos antes de cortar.', 35, 'El reposo permite cortar porciones limpias'),
    ],
  },
  {
    id: 15,
    titulo: 'Ceviche Peruano',
    autor: 'elena',
    imagenUrl: img('photo-1596797038530-2c107229654b'),
    categoria: 'Pescado',
    dificultad: 'Fácil',
    tiempoTotal: 20, tiempoPreparacion: 20, tiempoCoccion: 0,
    porciones: 4,
    etiquetas: ['Peruana', 'Fresco', 'Sin Cocción'],
    descripcion: 'Pescado fresco marinado en lima con cebolla morada y ají. Un plato limpio, ácido y lleno de frescura.',
    nutricion: nut(220, 28, 16, 4, 2, 4, 480),
    valoracionObjetivo: 4.7,
    ingredientes: [
      ing('Corvina', 600, 'g', 'Corvina', 'muy fresca, sin piel ni espinas'),
      ing('Limas', 8, 'unidades', 'Lima'),
      ing('Cebolla morada', 1, 'unidad', 'Cebolla morada', 'en juliana fina'),
      ing('Ají o guindilla', 1, 'unidad', 'Guindilla fresca', 'sin semillas'),
      ing('Cilantro fresco', 0.5, 'taza', 'Cilantro fresco'),
      ing('Ajo', 1, 'diente', 'Ajo'),
      ing('Jengibre fresco', 1, 'cucharadita', 'Jengibre fresco'),
      ing('Maíz dulce', 150, 'g', 'Maíz dulce', 'para acompañar'),
      ing('Patata o boniato', 2, 'unidades', 'Patata', 'cocido, para acompañar'),
      ing('Sal', null, 'al gusto', 'Sal'),
    ],
    pasos: [
      paso('Cortar el pescado', 'Corta el pescado en dados de 2 cm y sálalo ligeramente.', 5, 'El pescado debe estar muy frío'),
      paso('Preparar la leche de tigre', 'Exprime las limas y mézclalas con el ajo, el jengibre y un poco de ají machacados.', 5, 'No exprimas las limas hasta el final o amargará'),
      paso('Marinar', 'Mezcla el pescado con la leche de tigre, la cebolla y el cilantro. Deja reposar solo unos minutos.', 5, 'Un ceviche fresco se marina 5-10 minutos, no horas'),
      paso('Servir', 'Sirve con el maíz y la patata cocida.', 5),
    ],
  },
  {
    id: 16,
    titulo: 'Pad Thai Vegetariano',
    autor: 'sofia',
    imagenUrl: img('photo-1559314809-0f31657def5e'),
    categoria: 'Asiática',
    dificultad: 'Medio',
    tiempoTotal: 25, tiempoPreparacion: 10, tiempoCoccion: 15,
    porciones: 2,
    etiquetas: ['Tailandesa', 'Vegetariana', 'Salteado'],
    descripcion: 'Fideos de arroz salteados con tofu, brotes de soja y salsa de tamarindo. Agridulce, rápido y adictivo.',
    nutricion: nut(380, 18, 52, 12, 5, 9, 880),
    valoracionObjetivo: 4.4,
    ingredientes: [
      ing('Fideos de arroz', 200, 'g', 'Fideos de arroz'),
      ing('Tofu firme', 200, 'g', 'Tofu firme', 'en dados'),
      ing('Huevos', 2, 'unidades', 'Huevo'),
      ing('Brotes de soja', 100, 'g', 'Brotes de soja'),
      ing('Zanahoria', 1, 'unidad', 'Zanahoria', 'en juliana'),
      ing('Cebolleta', 0.5, 'unidad', 'Cebolla'),
      ing('Ajo', 2, 'dientes', 'Ajo'),
      ing('Salsa de tamarindo', 2, 'cucharadas', 'Salsa de tamarindo'),
      ing('Salsa de soja', 2, 'cucharadas', 'Salsa de soja'),
      ing('Azúcar moreno', 1, 'cucharada', 'Azúcar moreno'),
      ing('Lima', 1, 'unidad', 'Lima'),
      ing('Cacahuetes', 40, 'g', 'Cacahuetes', 'tostados y picados'),
      ing('Aceite de girasol', 2, 'cucharadas', 'Aceite de girasol'),
      ing('Cilantro fresco', null, 'al gusto', 'Cilantro fresco'),
    ],
    pasos: [
      paso('Remojar los fideos', 'Remoja los fideos en agua caliente hasta que estén flexibles pero firmes. Escúrrelos.', 10, 'No los cuezas del todo: terminarán en la sartén'),
      paso('Preparar la salsa', 'Mezcla el tamarindo, la soja y el azúcar hasta disolver.', 3),
      paso('Saltear el tofu y las verduras', 'Dora el tofu en aceite muy caliente, añade el ajo, la zanahoria y la cebolleta y saltea un par de minutos.', 7, 'Un wok bien caliente es la clave'),
      paso('Terminar el pad thai', 'Añade los fideos y la salsa, saltea, incorpora el huevo batido y los brotes. Sirve con cacahuetes, lima y cilantro.', 5),
    ],
  },
  {
    id: 17,
    titulo: 'Chili con Carne',
    autor: 'elena',
    imagenUrl: img('photo-1578662996442-48f60103fc96'),
    categoria: 'Americana',
    dificultad: 'Fácil',
    tiempoTotal: 120, tiempoPreparacion: 15, tiempoCoccion: 105,
    porciones: 6,
    etiquetas: ['Americana', 'Picante', 'Guiso'],
    descripcion: 'Guiso texano de carne de ternera con alubias rojas y especias. Mejora al día siguiente.',
    nutricion: nut(480, 36, 28, 24, 8, 7, 690),
    valoracionObjetivo: 4.6,
    ingredientes: [
      ing('Carne picada de ternera', 800, 'g', 'Carne picada de ternera'),
      ing('Alubias rojas cocidas', 400, 'g', 'Alubias rojas cocidas'),
      ing('Tomate triturado', 500, 'g', 'Tomate triturado'),
      ing('Cebolla', 2, 'unidades', 'Cebolla'),
      ing('Pimiento rojo', 1, 'unidad', 'Pimiento rojo'),
      ing('Ajo', 3, 'dientes', 'Ajo'),
      ing('Guindilla fresca', 2, 'unidades', 'Guindilla fresca', 'o chile en polvo'),
      ing('Comino', 2, 'cucharaditas', 'Comino'),
      ing('Pimentón', 1, 'cucharada', 'Pimentón'),
      ing('Orégano seco', 1, 'cucharadita', 'Orégano seco'),
      ing('Caldo de pollo', 300, 'ml', 'Caldo de pollo'),
      ing('Aceite de oliva virgen extra', 2, 'cucharadas', 'Aceite de oliva virgen extra'),
      ing('Cacao en polvo', 1, 'cucharadita', 'Cacao en polvo', 'el secreto para dar profundidad'),
      ing('Sal', null, 'al gusto', 'Sal'),
    ],
    pasos: [
      paso('Hacer el sofrito', 'Sofríe la cebolla, el pimiento, el ajo y la guindilla en aceite hasta que estén blandos.', 10),
      paso('Dorar la carne', 'Añade la carne y dórala bien, deshaciendo los grumos.', 10, 'Deja que se tueste; ahí está el sabor'),
      paso('Guisar', 'Incorpora las especias, el cacao, el tomate y el caldo. Cocina a fuego lento con la tapa entreabierta.', 90, 'Cuanto más lento, mejor'),
      paso('Añadir las alubias', 'Agrega las alubias escurridas los últimos 10 minutos y rectifica de sal.', 10, 'Sirve con arroz, nachos o pan de maíz'),
    ],
  },
  {
    id: 18,
    titulo: 'Quiche Lorraine',
    autor: 'marco',
    imagenUrl: img('photo-1565958011703-44f9829ba187'),
    categoria: 'Francesa',
    dificultad: 'Medio',
    tiempoTotal: 50, tiempoPreparacion: 15, tiempoCoccion: 35,
    porciones: 6,
    etiquetas: ['Francesa', 'Hornear', 'Brunch'],
    descripcion: 'Tarta salada francesa con bacon, gruyère y una crema de huevo y nata. Perfecta para un brunch.',
    nutricion: nut(420, 16, 22, 31, 1, 3, 620),
    valoracionObjetivo: 4.5,
    ingredientes: [
      ing('Masa quebrada', 250, 'g', 'Masa quebrada'),
      ing('Bacon', 200, 'g', 'Bacon', 'en tiras'),
      ing('Huevos', 4, 'unidades', 'Huevo'),
      ing('Nata para cocinar', 250, 'ml', 'Nata para cocinar'),
      ing('Leche entera', 100, 'ml', 'Leche entera'),
      ing('Queso gruyère', 150, 'g', 'Queso gruyère', 'rallado'),
      ing('Cebolla', 1, 'unidad', 'Cebolla', 'opcional'),
      ing('Sal, pimienta y nuez moscada', null, 'al gusto'),
    ],
    pasos: [
      paso('Preparar la base', 'Forra un molde con la masa, pincha el fondo y hornéala en blanco a 180 °C.', 12, 'Hornear la base evita que quede cruda'),
      paso('Dorar el bacon', 'Dora el bacon (y la cebolla si la usas) en una sartén y escúrrelo.', 6),
      paso('Hacer la crema', 'Bate los huevos con la nata, la leche, sal, pimienta y nuez moscada.', 4),
      paso('Rellenar y hornear', 'Reparte el bacon y el queso sobre la base, vierte la crema y hornea hasta que cuaje y se dore.', 30, 'Deja templar antes de cortar'),
    ],
  },
  {
    id: 19,
    titulo: 'Falafel con Hummus',
    autor: 'sofia',
    imagenUrl: img('photo-1593504049359-74330189a345'),
    categoria: 'Medio Oriental',
    dificultad: 'Medio',
    tiempoTotal: 30, tiempoPreparacion: 15, tiempoCoccion: 15,
    porciones: 4,
    etiquetas: ['Vegana', 'Medio Oriental', 'Proteína'],
    descripcion: 'Bolitas crujientes de garbanzo especiadas con hummus cremoso casero. Proteína vegetal en su mejor versión.',
    nutricion: nut(350, 13, 38, 17, 9, 4, 520),
    valoracionObjetivo: 4.4,
    ingredientes: [
      ing('Garbanzos cocidos', 600, 'g', 'Garbanzos cocidos', '400 g para el falafel y 200 g para el hummus'),
      ing('Cebolla', 1, 'unidad', 'Cebolla'),
      ing('Ajo', 4, 'dientes', 'Ajo'),
      ing('Perejil fresco', 1, 'taza', 'Perejil fresco'),
      ing('Cilantro fresco', 0.5, 'taza', 'Cilantro fresco'),
      ing('Comino', 2, 'cucharaditas', 'Comino'),
      ing('Harina de trigo', 3, 'cucharadas', 'Harina de trigo'),
      ing('Tahini', 4, 'cucharadas', 'Tahini'),
      ing('Limón', 1, 'unidad', 'Limón', 'su zumo'),
      ing('Aceite de oliva virgen extra', 3, 'cucharadas', 'Aceite de oliva virgen extra'),
      ing('Aceite de girasol', 300, 'ml', 'Aceite de girasol', 'para freír'),
      ing('Sal', null, 'al gusto', 'Sal'),
    ],
    pasos: [
      paso('Hacer la masa de falafel', 'Tritura 400 g de garbanzos con la cebolla, 2 dientes de ajo, las hierbas, el comino, la harina y sal hasta obtener una masa gruesa.', 10, 'No la hagas puré: debe tener textura'),
      paso('Formar y freír', 'Forma bolitas y fríelas en aceite caliente hasta que estén doradas y crujientes.', 10, 'Si se deshacen, añade un poco más de harina'),
      paso('Preparar el hummus', 'Tritura el resto de garbanzos con el tahini, el zumo de limón, el ajo restante, aceite de oliva y sal.', 5, 'Añade agua fría para una textura más ligera'),
      paso('Servir', 'Sirve el falafel sobre el hummus con un hilo de aceite y pan de pita.', 5),
    ],
  },
  {
    id: 20,
    titulo: 'Tiramisú Clásico',
    autor: 'giuseppe',
    imagenUrl: img('photo-1571877227200-a0d98ea607e9'),
    categoria: 'Postre',
    dificultad: 'Medio',
    tiempoTotal: 30, tiempoPreparacion: 30, tiempoCoccion: 0,
    porciones: 8,
    etiquetas: ['Italiana', 'Postre', 'Café'],
    descripcion: 'El postre italiano por excelencia: capas de bizcocho empapado en café, crema de mascarpone y cacao.',
    nutricion: nut(420, 9, 34, 28, 1, 22, 95),
    valoracionObjetivo: 4.8,
    ingredientes: [
      ing('Queso mascarpone', 500, 'g', 'Queso mascarpone'),
      ing('Huevos', 4, 'unidades', 'Huevo', 'muy frescos'),
      ing('Azúcar blanco', 100, 'g', 'Azúcar blanco'),
      ing('Bizcochos savoiardi', 300, 'g', 'Bizcochos savoiardi'),
      ing('Café espresso', 300, 'ml', 'Café espresso', 'frío'),
      ing('Cacao en polvo', 2, 'cucharadas', 'Cacao en polvo'),
      ing('Sal', null, 'pizca', 'Sal'),
    ],
    pasos: [
      paso('Hacer la crema', 'Bate las yemas con el azúcar hasta blanquear e incorpora el mascarpone. Monta las claras con una pizca de sal y mézclalas con suavidad.', 10, 'Movimientos envolventes para no perder aire'),
      paso('Mojar los bizcochos', 'Baña los savoiardi brevemente en el café frío.', 5, 'Un segundo por cara: no deben empaparse'),
      paso('Montar', 'Alterna capas de bizcocho y crema en una fuente, terminando con crema.', 10),
      paso('Reposar', 'Refrigera al menos 4 horas y espolvorea con cacao antes de servir.', 5, 'De un día para otro está aún mejor'),
    ],
  },
];
