// Tablas de traducción para importar desde TheMealDB (inglés -> español).
// INGREDIENTES: clave en minúsculas tal como la usa TheMealDB; valor [nombre en español, nombre en
// nuestra tabla de alimentos o null si no existe]. Los no listados se importan con su nombre en inglés.

export const CATEGORIAS = {
  Beef: 'Ternera',
  Breakfast: 'Desayuno',
  Chicken: 'Pollo',
  Dessert: 'Postre',
  Goat: 'Cabra',
  Lamb: 'Cordero',
  Miscellaneous: 'Varios',
  Pasta: 'Pasta',
  Pork: 'Cerdo',
  Seafood: 'Pescado',
  Side: 'Guarnición',
  Starter: 'Aperitivo',
  Vegan: 'Vegana',
  Vegetarian: 'Vegetariana',
};

export const COCINAS = {
  American: 'Americana', British: 'Británica', Canadian: 'Canadiense', Chinese: 'China', Croatian: 'Croata',
  Dutch: 'Holandesa', Egyptian: 'Egipcia', Filipino: 'Filipina', French: 'Francesa', Greek: 'Griega',
  Indian: 'India', Irish: 'Irlandesa', Italian: 'Italiana', Jamaican: 'Jamaicana', Japanese: 'Japonesa',
  Kenyan: 'Keniana', Malaysian: 'Malaya', Mexican: 'Mexicana', Moroccan: 'Marroquí', Norwegian: 'Noruega',
  Polish: 'Polaca', Portuguese: 'Portuguesa', Russian: 'Rusa', Spanish: 'Española', Thai: 'Tailandesa',
  Tunisian: 'Tunecina', Turkish: 'Turca', Ukrainian: 'Ucraniana', Uruguayan: 'Uruguaya', Vietnamese: 'Vietnamita',
  'Saudi Arabian': 'Saudí', Syrian: 'Siria', Algerian: 'Argelina', Australian: 'Australiana', Argentine: 'Argentina',
  Brazilian: 'Brasileña', Cuban: 'Cubana', Lebanese: 'Libanesa', Peruvian: 'Peruana', Venezuelan: 'Venezolana',
  Colombian: 'Colombiana', Chilean: 'Chilena', Pakistani: 'Pakistaní', Bangladeshi: 'Bangladesí', Nigerian: 'Nigeriana',
  'South African': 'Sudafricana', German: 'Alemana', Austrian: 'Austriaca', Swiss: 'Suiza', Swedish: 'Sueca',
  Danish: 'Danesa', Finnish: 'Finlandesa', Hungarian: 'Húngara', Czech: 'Checa', 'South Korean': 'Coreana',
  Korean: 'Coreana', Indonesian: 'Indonesia', Singaporean: 'Singapurense', Israeli: 'Israelí', Iranian: 'Iraní',
  Ethiopian: 'Etíope', Ghanaian: 'Ghanesa', Cambodian: 'Camboyana', 'Sri Lankan': 'Ceilanesa', Belgian: 'Belga',
  Scottish: 'Escocesa', Welsh: 'Galesa', Caribbean: 'Caribeña', Unknown: null,
};

export const ETIQUETAS = {
  Meat: 'Carne', Casserole: 'Guiso', Pasta: 'Pasta', Curry: 'Curry', Spicy: 'Picante', Dessert: 'Postre',
  Baking: 'Horneado', Vegetarian: 'Vegetariana', Vegan: 'Vegana', Sweet: 'Dulce', Fish: 'Pescado', Soup: 'Sopa',
  Breakfast: 'Desayuno', Chicken: 'Pollo', Pie: 'Tarta', Cake: 'Bizcocho', Pudding: 'Pudin', Snack: 'Tentempié',
  Christmas: 'Navidad', Alcoholic: 'Con alcohol', Treat: 'Capricho', Sandwich: 'Sándwich', StreetFood: 'Callejera',
  Streetfood: 'Callejera', Dairy: 'Lácteos', Nutty: 'Frutos secos', Speciality: 'Especialidad', Light: 'Ligera',
  Fusion: 'Fusión', BBQ: 'Barbacoa', Bbq: 'Barbacoa', Bun: 'Bollo', Brunch: 'Brunch', Salad: 'Ensalada',
  Halloween: 'Halloween', Summer: 'Verano', Savory: 'Salado', Vegetables: 'Verduras', Fresh: 'Fresco',
  Sausages: 'Salchichas', Lamb: 'Cordero', Beans: 'Legumbres', Onion: 'Cebolla', Egg: 'Huevo', Seafood: 'Marisco',
  Shellfish: 'Marisco', Warm: 'Caliente', Chilli: 'Picante', Glazed: 'Glaseado', Caramel: 'Caramelo',
  Fruity: 'Afrutado', Tart: 'Tarta', Sour: 'Ácido', Kebab: 'Kebab', Rice: 'Arroz', Grill: 'Parrilla',
  Greasy: 'Contundente', Heavy: 'Contundente', Mild: 'Suave', Pork: 'Cerdo', Beef: 'Ternera', Lunch: 'Comida',
  Dinner: 'Cena', Stew: 'Guiso', Paella: 'Paella', Tapas: 'Tapas', Sidedish: 'Guarnición', SideDish: 'Guarnición',
  Cheasy: 'Con queso', Cheese: 'Queso', Bread: 'Pan', Cheap: 'Económica', Easy: 'Fácil', Quick: 'Rápida',
  Comfort: 'Comfort Food', Traditional: 'Tradicional',
};

// [español, alimento en nuestra tabla | null]
export const INGREDIENTES = {
  // Carnes y aves
  chicken: ['Pollo', 'Pollo entero'],
  'whole chicken': ['Pollo entero', 'Pollo entero'],
  'chicken breast': ['Pechuga de pollo', 'Pechuga de pollo'],
  'chicken breasts': ['Pechuga de pollo', 'Pechuga de pollo'],
  'chicken thighs': ['Muslos de pollo', 'Muslo de pollo'],
  'chicken thigh': ['Muslo de pollo', 'Muslo de pollo'],
  'chicken legs': ['Muslos de pollo', 'Muslo de pollo'],
  'chicken stock': ['Caldo de pollo', 'Caldo de pollo'],
  'chicken stock cube': ['Pastilla de caldo de pollo', null],
  beef: ['Ternera', 'Ternera magra'],
  'beef fillet': ['Solomillo de ternera', 'Ternera magra'],
  'beef brisket': ['Pecho de ternera', 'Ternera magra'],
  'minced beef': ['Carne picada de ternera', 'Carne picada de ternera'],
  'beef mince': ['Carne picada de ternera', 'Carne picada de ternera'],
  'ground beef': ['Carne picada de ternera', 'Carne picada de ternera'],
  'lean minced beef': ['Carne picada de ternera', 'Carne picada de ternera'],
  'beef stock': ['Caldo de carne', null],
  'beef stock concentrate': ['Concentrado de caldo de carne', null],
  steak: ['Filete de ternera', 'Ternera magra'],
  'rump steak': ['Filete de cadera', 'Ternera magra'],
  'sirloin steak': ['Entrecot', 'Ternera magra'],
  pork: ['Cerdo', 'Lomo de cerdo'],
  'pork chops': ['Chuletas de cerdo', 'Lomo de cerdo'],
  'pork belly': ['Panceta de cerdo', 'Panceta'],
  'pork shoulder': ['Paletilla de cerdo', 'Lomo de cerdo'],
  'minced pork': ['Carne picada de cerdo', 'Lomo de cerdo'],
  'pork mince': ['Carne picada de cerdo', 'Lomo de cerdo'],
  bacon: ['Bacon', 'Bacon'],
  'streaky bacon': ['Bacon', 'Bacon'],
  'smoked bacon': ['Bacon ahumado', 'Bacon'],
  pancetta: ['Panceta', 'Panceta'],
  ham: ['Jamón', 'Jamón serrano'],
  prosciutto: ['Jamón curado', 'Jamón serrano'],
  'parma ham': ['Jamón de Parma', 'Jamón serrano'],
  chorizo: ['Chorizo', 'Chorizo'],
  sausages: ['Salchichas', null],
  'italian sausages': ['Salchichas italianas', null],
  lamb: ['Cordero', null],
  'lamb mince': ['Carne picada de cordero', null],
  'lamb leg': ['Pierna de cordero', null],
  'lamb shoulder': ['Paletilla de cordero', null],
  'lamb loin chops': ['Chuletas de cordero', null],
  turkey: ['Pavo', null],
  'turkey mince': ['Carne picada de pavo', null],
  duck: ['Pato', null],
  'duck legs': ['Muslos de pato', null],
  'goat meat': ['Carne de cabra', null],
  goat: ['Cabra', null],
  'ground pork': ['Carne picada de cerdo', 'Lomo de cerdo'],
  lard: ['Manteca de cerdo', null],
  // Frecuentes en TheMealDB
  allspice: ['Pimienta de Jamaica', null],
  'melted butter': ['Mantequilla derretida', 'Mantequilla'],
  'scotch bonnet': ['Chile scotch bonnet', 'Guindilla fresca'],
  scallions: ['Cebolletas', 'Cebolla'],
  'kosher salt': ['Sal gruesa', 'Sal'],
  'garlic powder': ['Ajo en polvo', null],
  'onion powder': ['Cebolla en polvo', null],
  'clear honey': ['Miel', 'Miel'],
  hotsauce: ['Salsa picante', null],
  'hot sauce': ['Salsa picante', null],
  'dry sherry': ['Jerez seco', 'Vino blanco'],
  'white cabbage': ['Repollo', 'Lombarda'],
  'harissa spice': ['Harissa', null],
  'coriander leaves': ['Hojas de cilantro', 'Cilantro fresco'],
  'red pepper flakes': ['Copos de guindilla', null],
  'dulce de leche': ['Dulce de leche', null],
  'vegetable stock cube': ['Pastilla de caldo de verduras', 'Caldo de verduras'],
  'sherry vinegar': ['Vinagre de Jerez', 'Vinagre de Jerez'],
  'golden caster sugar': ['Azúcar fino dorado', 'Azúcar blanco'],
  'ground nutmeg': ['Nuez moscada molida', null],
  'egg plants': ['Berenjenas', 'Berenjena'],
  'black treacle': ['Melaza', null],
  challots: ['Chalotas', 'Cebollitas francesas'],
  rocket: ['Rúcula', 'Lechuga romana'],
  marjoram: ['Mejorana', null],
  // Pescados y mariscos
  salmon: ['Salmón', 'Salmón'],
  'salmon fillets': ['Filetes de salmón', 'Salmón'],
  'smoked salmon': ['Salmón ahumado', 'Salmón'],
  cod: ['Bacalao', 'Bacalao'],
  'cod fillets': ['Filetes de bacalao', 'Bacalao'],
  haddock: ['Eglefino', 'Bacalao'],
  'white fish': ['Pescado blanco', 'Merluza'],
  'white fish fillets': ['Filetes de pescado blanco', 'Merluza'],
  'sea bass': ['Lubina', 'Lubina'],
  tuna: ['Atún', 'Atún en conserva al natural'],
  'tuna steak': ['Filete de atún', 'Atún fresco'],
  prawns: ['Gambas', 'Gambas'],
  'king prawns': ['Langostinos', 'Gambas'],
  'raw king prawns': ['Langostinos crudos', 'Gambas'],
  'tiger prawns': ['Langostinos tigre', 'Gambas'],
  shrimp: ['Gambas', 'Gambas'],
  mussels: ['Mejillones', 'Mejillones'],
  squid: ['Calamar', 'Calamar'],
  clams: ['Almejas', 'Mejillones'],
  scallops: ['Vieiras', null],
  crab: ['Cangrejo', null],
  'crab meat': ['Carne de cangrejo', 'Surimi'],
  anchovy: ['Anchoa', 'Anchoas en aceite'],
  anchovies: ['Anchoas', 'Anchoas en aceite'],
  'anchovy fillets': ['Filetes de anchoa', 'Anchoas en aceite'],
  mackerel: ['Caballa', null],
  sardines: ['Sardinas', null],
  // Huevos y lácteos
  egg: ['Huevo', 'Huevo'],
  eggs: ['Huevos', 'Huevo'],
  'egg yolks': ['Yemas de huevo', 'Yema de huevo'],
  'egg yolk': ['Yema de huevo', 'Yema de huevo'],
  'egg white': ['Clara de huevo', null],
  'egg whites': ['Claras de huevo', null],
  milk: ['Leche', 'Leche entera'],
  'whole milk': ['Leche entera', 'Leche entera'],
  'coconut milk': ['Leche de coco', 'Leche de coco'],
  'coconut cream': ['Crema de coco', 'Leche de coco'],
  cream: ['Nata', 'Nata para cocinar'],
  'double cream': ['Nata para montar', 'Nata para cocinar'],
  'single cream': ['Nata líquida', 'Nata para cocinar'],
  'heavy cream': ['Nata para montar', 'Nata para cocinar'],
  'sour cream': ['Nata agria', 'Nata para cocinar'],
  'creme fraiche': ['Crème fraîche', 'Nata para cocinar'],
  butter: ['Mantequilla', 'Mantequilla'],
  'unsalted butter': ['Mantequilla sin sal', 'Mantequilla'],
  'salted butter': ['Mantequilla con sal', 'Mantequilla'],
  cheese: ['Queso', 'Queso mozzarella'],
  'cheddar cheese': ['Queso cheddar', 'Queso gruyère'],
  cheddar: ['Queso cheddar', 'Queso gruyère'],
  parmesan: ['Queso parmesano', 'Queso parmesano'],
  'parmesan cheese': ['Queso parmesano', 'Queso parmesano'],
  'grated parmesan': ['Queso parmesano rallado', 'Queso parmesano'],
  mozzarella: ['Mozzarella', 'Queso mozzarella'],
  'mozzarella balls': ['Bolas de mozzarella', 'Queso mozzarella'],
  feta: ['Queso feta', 'Queso ricotta'],
  'feta cheese': ['Queso feta', 'Queso ricotta'],
  ricotta: ['Ricotta', 'Queso ricotta'],
  mascarpone: ['Mascarpone', 'Queso mascarpone'],
  'cream cheese': ['Queso crema', 'Queso mascarpone'],
  'goats cheese': ['Queso de cabra', null],
  gruyere: ['Queso gruyère', 'Queso gruyère'],
  yogurt: ['Yogur', 'Yogur natural'],
  'greek yogurt': ['Yogur griego', 'Yogur natural'],
  'natural yogurt': ['Yogur natural', 'Yogur natural'],
  // Verduras y hortalizas
  onion: ['Cebolla', 'Cebolla'],
  onions: ['Cebollas', 'Cebolla'],
  'red onion': ['Cebolla morada', 'Cebolla morada'],
  'red onions': ['Cebollas moradas', 'Cebolla morada'],
  'white onion': ['Cebolla blanca', 'Cebolla'],
  shallots: ['Chalotas', 'Cebollitas francesas'],
  shallot: ['Chalota', 'Cebollitas francesas'],
  'spring onions': ['Cebolletas', 'Cebolla'],
  'spring onion': ['Cebolleta', 'Cebolla'],
  leek: ['Puerro', null],
  leeks: ['Puerros', null],
  garlic: ['Ajo', 'Ajo'],
  'garlic clove': ['Diente de ajo', 'Ajo'],
  'garlic cloves': ['Dientes de ajo', 'Ajo'],
  'minced garlic': ['Ajo picado', 'Ajo'],
  ginger: ['Jengibre', 'Jengibre fresco'],
  'ginger paste': ['Pasta de jengibre', 'Jengibre fresco'],
  'ground ginger': ['Jengibre molido', null],
  tomato: ['Tomate', 'Tomate'],
  tomatoes: ['Tomates', 'Tomate'],
  'cherry tomatoes': ['Tomates cherry', 'Tomates cherry'],
  'plum tomatoes': ['Tomates pera', 'Tomate'],
  'chopped tomatoes': ['Tomate troceado en conserva', 'Tomate triturado'],
  'canned tomatoes': ['Tomate en conserva', 'Tomate triturado'],
  'tinned tomatos': ['Tomate en conserva', 'Tomate triturado'],
  'tomato puree': ['Concentrado de tomate', 'Tomate triturado'],
  'tomato paste': ['Concentrado de tomate', 'Tomate triturado'],
  passata: ['Tomate triturado', 'Tomate triturado'],
  'tomato sauce': ['Salsa de tomate', 'Tomate triturado'],
  'tomato ketchup': ['Kétchup', null],
  ketchup: ['Kétchup', null],
  potatoes: ['Patatas', 'Patata'],
  potato: ['Patata', 'Patata'],
  'new potatoes': ['Patatas nuevas', 'Patata'],
  'sweet potatoes': ['Boniatos', 'Patata'],
  'sweet potato': ['Boniato', 'Patata'],
  carrots: ['Zanahorias', 'Zanahoria'],
  carrot: ['Zanahoria', 'Zanahoria'],
  celery: ['Apio', null],
  peas: ['Guisantes', 'Judías verdes'],
  'frozen peas': ['Guisantes congelados', 'Judías verdes'],
  'green beans': ['Judías verdes', 'Judías verdes'],
  spinach: ['Espinacas', 'Espinacas'],
  'baby spinach': ['Espinacas baby', 'Espinacas'],
  broccoli: ['Brócoli', 'Brócoli'],
  cauliflower: ['Coliflor', 'Brócoli'],
  mushrooms: ['Champiñones', 'Champiñones'],
  'chestnut mushroom': ['Champiñones portobello', 'Champiñones'],
  'shiitake mushrooms': ['Setas shiitake', 'Setas variadas'],
  'wild mushrooms': ['Setas silvestres', 'Setas variadas'],
  courgettes: ['Calabacines', 'Calabacín'],
  courgette: ['Calabacín', 'Calabacín'],
  zucchini: ['Calabacín', 'Calabacín'],
  aubergine: ['Berenjena', 'Berenjena'],
  eggplant: ['Berenjena', 'Berenjena'],
  peppers: ['Pimientos', 'Pimiento rojo'],
  'red pepper': ['Pimiento rojo', 'Pimiento rojo'],
  'red peppers': ['Pimientos rojos', 'Pimiento rojo'],
  'green pepper': ['Pimiento verde', 'Pimiento verde'],
  'yellow pepper': ['Pimiento amarillo', 'Pimiento rojo'],
  'red chilli': ['Guindilla roja', 'Guindilla fresca'],
  'red chili': ['Guindilla roja', 'Guindilla fresca'],
  'green chilli': ['Guindilla verde', 'Guindilla fresca'],
  chilli: ['Guindilla', 'Guindilla fresca'],
  'red chilli flakes': ['Copos de guindilla', null],
  'chilli flakes': ['Copos de guindilla', null],
  jalapeno: ['Jalapeño', 'Guindilla fresca'],
  lettuce: ['Lechuga', 'Lechuga romana'],
  'little gem lettuce': ['Cogollos de lechuga', 'Lechuga romana'],
  cucumber: ['Pepino', 'Pepino'],
  avocado: ['Aguacate', 'Aguacate'],
  cabbage: ['Repollo', 'Lombarda'],
  'red cabbage': ['Lombarda', 'Lombarda'],
  kale: ['Kale', 'Espinacas'],
  sweetcorn: ['Maíz dulce', 'Maíz dulce'],
  corn: ['Maíz', 'Maíz dulce'],
  beansprouts: ['Brotes de soja', 'Brotes de soja'],
  'bean sprouts': ['Brotes de soja', 'Brotes de soja'],
  asparagus: ['Espárragos', 'Judías verdes'],
  pumpkin: ['Calabaza', null],
  'butternut squash': ['Calabaza', null],
  beetroot: ['Remolacha', null],
  radish: ['Rábano', null],
  olives: ['Aceitunas', null],
  'black olives': ['Aceitunas negras', null],
  'green olives': ['Aceitunas verdes', null],
  capers: ['Alcaparras', null],
  // Hierbas y especias
  parsley: ['Perejil', 'Perejil fresco'],
  'fresh parsley': ['Perejil fresco', 'Perejil fresco'],
  'flat leaf parsley': ['Perejil de hoja plana', 'Perejil fresco'],
  coriander: ['Cilantro', 'Cilantro fresco'],
  'fresh coriander': ['Cilantro fresco', 'Cilantro fresco'],
  cilantro: ['Cilantro', 'Cilantro fresco'],
  'ground coriander': ['Cilantro molido', null],
  'coriander seeds': ['Semillas de cilantro', null],
  basil: ['Albahaca', 'Albahaca fresca'],
  'basil leaves': ['Hojas de albahaca', 'Albahaca fresca'],
  'fresh basil': ['Albahaca fresca', 'Albahaca fresca'],
  thyme: ['Tomillo', null],
  'fresh thyme': ['Tomillo fresco', null],
  rosemary: ['Romero', null],
  oregano: ['Orégano', 'Orégano seco'],
  'dried oregano': ['Orégano seco', 'Orégano seco'],
  'bay leaf': ['Hoja de laurel', null],
  'bay leaves': ['Hojas de laurel', null],
  mint: ['Menta', null],
  'fresh mint': ['Menta fresca', null],
  dill: ['Eneldo', null],
  chives: ['Cebollino', null],
  sage: ['Salvia', null],
  lemongrass: ['Hierba limón', null],
  salt: ['Sal', 'Sal'],
  'sea salt': ['Sal marina', 'Sal'],
  pepper: ['Pimienta', 'Pimienta negra'],
  'black pepper': ['Pimienta negra', 'Pimienta negra'],
  'ground black pepper': ['Pimienta negra molida', 'Pimienta negra'],
  'white pepper': ['Pimienta blanca', 'Pimienta negra'],
  'salt and pepper': ['Sal y pimienta', null],
  paprika: ['Pimentón', 'Pimentón'],
  'smoked paprika': ['Pimentón ahumado', 'Pimentón'],
  cumin: ['Comino', 'Comino'],
  'ground cumin': ['Comino molido', 'Comino'],
  'cumin seeds': ['Semillas de comino', 'Comino'],
  turmeric: ['Cúrcuma', null],
  'ground turmeric': ['Cúrcuma molida', null],
  'chilli powder': ['Guindilla en polvo', null],
  'chili powder': ['Chile en polvo', null],
  'cayenne pepper': ['Cayena', null],
  cinnamon: ['Canela', null],
  'cinnamon stick': ['Rama de canela', null],
  'ground cinnamon': ['Canela molida', null],
  nutmeg: ['Nuez moscada', null],
  cloves: ['Clavo', null],
  cardamom: ['Cardamomo', null],
  'star anise': ['Anís estrellado', null],
  'curry powder': ['Curry en polvo', 'Curry en polvo'],
  'garam masala': ['Garam masala', 'Curry en polvo'],
  'red curry paste': ['Pasta de curry rojo', 'Pasta de curry rojo'],
  'thai red curry paste': ['Pasta de curry rojo', 'Pasta de curry rojo'],
  'green curry paste': ['Pasta de curry verde', 'Pasta de curry rojo'],
  saffron: ['Azafrán', 'Azafrán'],
  'mustard seeds': ['Semillas de mostaza', null],
  'fennel seeds': ['Semillas de hinojo', null],
  'sesame seeds': ['Semillas de sésamo', 'Semillas de sésamo'],
  'mixed spice': ['Mezcla de especias', null],
  'five spice': ['Cinco especias', null],
  'vanilla extract': ['Extracto de vainilla', null],
  vanilla: ['Vainilla', null],
  // Cereales, pan y pasta
  rice: ['Arroz', 'Arroz blanco'],
  'basmati rice': ['Arroz basmati', 'Arroz blanco'],
  'jasmine rice': ['Arroz jazmín', 'Arroz blanco'],
  'brown rice': ['Arroz integral', 'Arroz blanco'],
  'long grain rice': ['Arroz de grano largo', 'Arroz blanco'],
  'arborio rice': ['Arroz arborio', 'Arroz arborio'],
  'paella rice': ['Arroz bomba', 'Arroz bomba'],
  'sushi rice': ['Arroz para sushi', 'Arroz blanco'],
  quinoa: ['Quinoa', 'Quinoa'],
  couscous: ['Cuscús', null],
  bulgur: ['Bulgur', null],
  spaghetti: ['Espaguetis', 'Espaguetis'],
  linguine: ['Linguine', 'Espaguetis'],
  penne: ['Penne', 'Espaguetis'],
  'penne rigate': ['Penne', 'Espaguetis'],
  fettuccine: ['Fettuccine', 'Espaguetis'],
  tagliatelle: ['Tagliatelle', 'Espaguetis'],
  macaroni: ['Macarrones', 'Espaguetis'],
  pasta: ['Pasta', 'Espaguetis'],
  'lasagne sheets': ['Placas de lasaña', 'Placas de lasaña'],
  'rice noodles': ['Fideos de arroz', 'Fideos de arroz'],
  'egg noodles': ['Fideos de huevo', 'Fideos ramen frescos'],
  noodles: ['Fideos', 'Fideos ramen frescos'],
  'udon noodles': ['Fideos udon', 'Fideos ramen frescos'],
  'rice vermicelli': ['Fideos vermicelli de arroz', 'Fideos de arroz'],
  bread: ['Pan', 'Pan de pueblo'],
  'white bread': ['Pan blanco', 'Pan de pueblo'],
  baguette: ['Baguette', 'Pan baguette'],
  'bread rolls': ['Panecillos', 'Pan de pueblo'],
  breadcrumbs: ['Pan rallado', 'Pan rallado'],
  'panko breadcrumbs': ['Panko', 'Pan rallado'],
  'pita bread': ['Pan de pita', 'Pan de pueblo'],
  tortillas: ['Tortillas', 'Tortillas de maíz'],
  'corn tortillas': ['Tortillas de maíz', 'Tortillas de maíz'],
  'flour tortilla': ['Tortilla de trigo', 'Tortillas de maíz'],
  'flour tortillas': ['Tortillas de trigo', 'Tortillas de maíz'],
  flour: ['Harina', 'Harina de trigo'],
  'plain flour': ['Harina de trigo', 'Harina de trigo'],
  'all purpose flour': ['Harina de trigo', 'Harina de trigo'],
  'self-raising flour': ['Harina con levadura', 'Harina de trigo'],
  'bread flour': ['Harina de fuerza', 'Harina de trigo'],
  cornstarch: ['Maicena', null],
  'corn flour': ['Maicena', null],
  cornflour: ['Maicena', null],
  'baking powder': ['Levadura química', null],
  'bicarbonate of soda': ['Bicarbonato', null],
  'baking soda': ['Bicarbonato', null],
  yeast: ['Levadura', null],
  oats: ['Copos de avena', null],
  'shortcrust pastry': ['Masa quebrada', 'Masa quebrada'],
  'puff pastry': ['Hojaldre', 'Masa quebrada'],
  'filo pastry': ['Masa filo', null],
  // Legumbres, frutos secos y semillas
  chickpeas: ['Garbanzos', 'Garbanzos cocidos'],
  'kidney beans': ['Alubias rojas', 'Alubias rojas cocidas'],
  'red kidney beans': ['Alubias rojas', 'Alubias rojas cocidas'],
  'black beans': ['Frijoles negros', 'Alubias rojas cocidas'],
  'cannellini beans': ['Alubias blancas', 'Alubias rojas cocidas'],
  'butter beans': ['Judiones', 'Alubias rojas cocidas'],
  'borlotti beans': ['Alubias pintas', 'Alubias rojas cocidas'],
  'baked beans': ['Alubias con tomate', 'Alubias rojas cocidas'],
  lentils: ['Lentejas', 'Lentejas cocidas'],
  'red lentils': ['Lentejas rojas', 'Lentejas cocidas'],
  'brown lentils': ['Lentejas pardinas', 'Lentejas cocidas'],
  tofu: ['Tofu', 'Tofu firme'],
  almonds: ['Almendras', 'Almendras'],
  'ground almonds': ['Almendra molida', 'Almendras'],
  'flaked almonds': ['Almendras laminadas', 'Almendras'],
  walnuts: ['Nueces', 'Nueces'],
  peanuts: ['Cacahuetes', 'Cacahuetes'],
  'peanut butter': ['Crema de cacahuete', 'Cacahuetes'],
  cashews: ['Anacardos', 'Almendras'],
  'cashew nuts': ['Anacardos', 'Almendras'],
  pistachios: ['Pistachos', 'Almendras'],
  'pine nuts': ['Piñones', 'Almendras'],
  'sunflower seeds': ['Semillas de girasol', 'Semillas de girasol'],
  tahini: ['Tahini', 'Tahini'],
  'desiccated coconut': ['Coco rallado', null],
  // Aceites, salsas y condimentos
  'olive oil': ['Aceite de oliva', 'Aceite de oliva virgen extra'],
  'extra virgin olive oil': ['Aceite de oliva virgen extra', 'Aceite de oliva virgen extra'],
  'vegetable oil': ['Aceite vegetal', 'Aceite de girasol'],
  'sunflower oil': ['Aceite de girasol', 'Aceite de girasol'],
  oil: ['Aceite', 'Aceite de girasol'],
  'sesame seed oil': ['Aceite de sésamo', 'Aceite de sésamo'],
  'sesame oil': ['Aceite de sésamo', 'Aceite de sésamo'],
  'coconut oil': ['Aceite de coco', null],
  'rapeseed oil': ['Aceite de colza', 'Aceite de girasol'],
  'soy sauce': ['Salsa de soja', 'Salsa de soja'],
  'dark soy sauce': ['Salsa de soja oscura', 'Salsa de soja'],
  'light soy sauce': ['Salsa de soja clara', 'Salsa de soja'],
  'fish sauce': ['Salsa de pescado', null],
  'oyster sauce': ['Salsa de ostras', null],
  'hoisin sauce': ['Salsa hoisin', null],
  'worcestershire sauce': ['Salsa Worcestershire', 'Salsa Worcestershire'],
  mirin: ['Mirin', 'Mirin'],
  sake: ['Sake', 'Vino blanco'],
  'rice vinegar': ['Vinagre de arroz', 'Vinagre de arroz'],
  'rice wine': ['Vino de arroz', 'Mirin'],
  vinegar: ['Vinagre', 'Vinagre de Jerez'],
  'white wine vinegar': ['Vinagre de vino blanco', 'Vinagre de Jerez'],
  'red wine vinegar': ['Vinagre de vino tinto', 'Vinagre de Jerez'],
  'balsamic vinegar': ['Vinagre balsámico', 'Vinagre de Jerez'],
  'apple cider vinegar': ['Vinagre de manzana', 'Vinagre de Jerez'],
  'cider vinegar': ['Vinagre de sidra', 'Vinagre de Jerez'],
  mustard: ['Mostaza', 'Mostaza de Dijon'],
  'dijon mustard': ['Mostaza de Dijon', 'Mostaza de Dijon'],
  'english mustard': ['Mostaza inglesa', 'Mostaza de Dijon'],
  'wholegrain mustard': ['Mostaza en grano', 'Mostaza de Dijon'],
  mayonnaise: ['Mayonesa', 'Mayonesa'],
  'miso paste': ['Pasta de miso', 'Pasta de miso'],
  miso: ['Miso', 'Pasta de miso'],
  'tamarind paste': ['Pasta de tamarindo', 'Salsa de tamarindo'],
  'sriracha': ['Sriracha', null],
  'harissa': ['Harissa', null],
  'chicken broth': ['Caldo de pollo', 'Caldo de pollo'],
  'vegetable stock': ['Caldo de verduras', 'Caldo de verduras'],
  'vegetable oil for frying': ['Aceite para freír', 'Aceite de girasol'],
  stock: ['Caldo', 'Caldo de verduras'],
  water: ['Agua', 'Agua'],
  'boiling water': ['Agua hirviendo', 'Agua'],
  // Dulces
  sugar: ['Azúcar', 'Azúcar blanco'],
  'caster sugar': ['Azúcar fino', 'Azúcar blanco'],
  'granulated sugar': ['Azúcar', 'Azúcar blanco'],
  'brown sugar': ['Azúcar moreno', 'Azúcar moreno'],
  'light brown soft sugar': ['Azúcar moreno', 'Azúcar moreno'],
  'dark brown soft sugar': ['Azúcar moreno oscuro', 'Azúcar moreno'],
  'demerara sugar': ['Azúcar demerara', 'Azúcar moreno'],
  'muscovado sugar': ['Azúcar mascabado', 'Azúcar moreno'],
  'icing sugar': ['Azúcar glas', 'Azúcar blanco'],
  honey: ['Miel', 'Miel'],
  'maple syrup': ['Sirope de arce', 'Miel'],
  'golden syrup': ['Sirope dorado', 'Miel'],
  'dark chocolate': ['Chocolate negro', 'Chocolate negro 70%'],
  'dark chocolate chips': ['Pepitas de chocolate negro', 'Chocolate negro 70%'],
  'milk chocolate': ['Chocolate con leche', 'Chocolate negro 70%'],
  'white chocolate': ['Chocolate blanco', null],
  'chocolate chips': ['Pepitas de chocolate', 'Chocolate negro 70%'],
  cocoa: ['Cacao en polvo', 'Cacao en polvo'],
  'cocoa powder': ['Cacao en polvo', 'Cacao en polvo'],
  'condensed milk': ['Leche condensada', null],
  'digestive biscuits': ['Galletas digestive', 'Bizcochos savoiardi'],
  'lady fingers': ['Bizcochos de soletilla', 'Bizcochos savoiardi'],
  // Frutas
  lemon: ['Limón', 'Limón'],
  lemons: ['Limones', 'Limón'],
  'lemon juice': ['Zumo de limón', 'Limón'],
  'lemon zest': ['Ralladura de limón', 'Limón'],
  lime: ['Lima', 'Lima'],
  limes: ['Limas', 'Lima'],
  'lime juice': ['Zumo de lima', 'Lima'],
  orange: ['Naranja', 'Naranja'],
  oranges: ['Naranjas', 'Naranja'],
  'orange juice': ['Zumo de naranja', 'Naranja'],
  'orange zest': ['Ralladura de naranja', 'Naranja'],
  apple: ['Manzana', 'Manzana'],
  apples: ['Manzanas', 'Manzana'],
  'bramley apples': ['Manzanas reineta', 'Manzana'],
  banana: ['Plátano', 'Plátano'],
  bananas: ['Plátanos', 'Plátano'],
  strawberries: ['Fresas', 'Fresas'],
  raspberries: ['Frambuesas', 'Fresas'],
  blueberries: ['Arándanos', 'Fresas'],
  mango: ['Mango', 'Mango'],
  pineapple: ['Piña', 'Mango'],
  raisins: ['Pasas', null],
  sultanas: ['Pasas sultanas', null],
  dates: ['Dátiles', null],
  coconut: ['Coco', null],
  // Bebidas
  'white wine': ['Vino blanco', 'Vino blanco'],
  'dry white wine': ['Vino blanco seco', 'Vino blanco'],
  'red wine': ['Vino tinto', 'Vino tinto'],
  beer: ['Cerveza', 'Cerveza'],
  lager: ['Cerveza rubia', 'Cerveza'],
  cider: ['Sidra', 'Cerveza'],
  brandy: ['Brandy', null],
  rum: ['Ron', null],
  'dark rum': ['Ron añejo', null],
  whisky: ['Whisky', null],
  'coffee': ['Café', 'Café espresso'],
  'espresso': ['Café espresso', 'Café espresso'],
  'instant coffee': ['Café soluble', 'Café espresso'],
};
